/**
 * Demo seed for the in-browser reference backend.
 *
 * The seeded world is generated by running the *real* domain logic (token
 * policy, settlement planning, ledger construction) against a set of demo
 * members, so the balances, transaction history and reviews in the UI are
 * internally consistent — not hand-written mock numbers. Nothing here is used
 * when `VITE_BACKEND_MODE=firebase`; a real deployment starts empty and grows
 * from real signups.
 */
import {
  DEFAULT_PLATFORM_CONFIG,
  bookingConfirmedDraft,
  buildSettlementWrites,
  computeTokenAmount,
  listingAfterBooking,
  listingAfterReview,
  listingAfterSettlement,
  mergeWindows,
  roundTokens,
  signupGrantAmount,
  commentReplyDraft,
  sessionSettledDraft,
  statsAfterReview,
  statsAfterSettlement,
  tokenGrantDraft,
  type NotificationDraft,
} from '@shared'
import {
  type AttendanceSegment,
  type Booking,
  type Community,
  type CommunityComment,
  type CommunityMember,
  type CommunityPost,
  type IsoDate,
  type PlatformConfig,
  type Review,
  type Room,
  type SkillListing,
  type UserProfile,
  type Wallet,
} from '@shared/domain'
import { slugify, type LocalDatabase } from './db'

/** Seed helpers: a broken demo fixture should fail loudly, not render blanks. */
function requireSeedUser(db: LocalDatabase, uid: string): UserProfile {
  const user = db.users[uid]
  if (!user) throw new Error(`seed: missing demo member ${uid}`)
  return user
}

function requireSeedBooking(db: LocalDatabase, id: string): Booking {
  const booking = db.bookings[id]
  if (!booking) throw new Error(`seed: missing demo booking ${id}`)
  return booking
}

const HOUR = 3_600_000
const DAY = 24 * HOUR

/** Every seeded account shares this password. Local demo mode only. */
export const DEMO_PASSWORD = 'peerpulse'

export const DEMO_CREDENTIALS = {
  member: { email: 'sam@peerpulse.app', password: DEMO_PASSWORD },
  admin: { email: 'admin@peerpulse.app', password: DEMO_PASSWORD },
} as const

/** Emails of every member the demo world seeds, so all of them can sign in. */
export function demoAccountEmails(db: LocalDatabase): string[] {
  return Object.values(db.users)
    .filter((user) => user.uid.startsWith('demo_'))
    .map((user) => user.email)
}

interface DemoMemberSpec {
  uid: string
  email: string
  displayName: string
  headline: string
  bio: string
  location: string
  timezone: string
  languages: string[]
  interests: string[]
  teach: Array<{ title: string; categoryId: string; level: SkillListing['level']; format: SkillListing['format']; duration: number; description: string; outcomes: string[]; tags: string[] }>
  learnCategories: string[]
  role?: 'member' | 'admin'
}

const MEMBERS: DemoMemberSpec[] = [
  {
    uid: 'demo_sam',
    email: DEMO_CREDENTIALS.member.email,
    displayName: 'Sam Okonkwo',
    headline: 'Guitarist trading riffs for code',
    bio: 'I have played guitar for 14 years and taught in community music schools. I am learning to build web apps, one session at a time.',
    location: 'Manchester, UK',
    timezone: 'Europe/London',
    languages: ['en'],
    interests: ['Learning a language', 'Creative practice', 'Community teaching'],
    teach: [
      {
        title: 'Guitar for absolute beginners',
        categoryId: 'music',
        level: 'beginner',
        format: 'video',
        duration: 60,
        description:
          'First chords, strumming patterns and how to practise in 15-minute blocks. Bring any acoustic guitar — no theory background needed.',
        outcomes: ['Play four open chords cleanly', 'Follow a simple strumming pattern', 'Build a 15-minute practice routine'],
        tags: ['guitar', 'acoustic', 'beginners'],
      },
      {
        title: 'Songwriting feedback session',
        categoryId: 'music',
        level: 'any',
        format: 'async',
        duration: 30,
        description: 'Send a demo or lyric sheet and get structured written feedback on structure, melody and imagery within 48 hours.',
        outcomes: ['Line-by-line feedback', 'Two rewrite suggestions', 'Arrangement ideas'],
        tags: ['songwriting', 'feedback'],
      },
    ],
    learnCategories: ['technology', 'languages'],
  },
  {
    uid: 'demo_lena',
    email: 'lena@peerpulse.app',
    displayName: 'Lena Fischer',
    headline: 'Frontend engineer, German conversation partner',
    bio: 'Vue and TypeScript by day. I teach plain-language web development and trade it for Spanish conversation practice.',
    location: 'Leipzig, Germany',
    timezone: 'Europe/Berlin',
    languages: ['de', 'en'],
    interests: ['Coding side projects', 'Mentoring beginners'],
    teach: [
      {
        title: 'Build your first Vue 3 app',
        categoryId: 'technology',
        level: 'beginner',
        format: 'video',
        duration: 90,
        description:
          'We scaffold a real project with Vite, add routing and state, then deploy it. You leave with a live URL and the mental model to keep going.',
        outcomes: ['Scaffold a Vue + Vite project', 'Understand components, props and state', 'Deploy to a public URL'],
        tags: ['vue', 'typescript', 'frontend'],
      },
      {
        title: 'German conversation, B1 to C1',
        categoryId: 'languages',
        level: 'intermediate',
        format: 'voice',
        duration: 45,
        description: 'Structured conversation with corrections on the fly and a written summary of your recurring mistakes afterwards.',
        outcomes: ['Speak without switching to English', 'Fix your top three recurring errors', 'Written recap with vocabulary'],
        tags: ['german', 'conversation'],
      },
    ],
    learnCategories: ['languages', 'design'],
  },
  {
    uid: 'demo_paulo',
    email: 'paulo@peerpulse.app',
    displayName: 'Paulo Cardoso',
    headline: 'Chef teaching knife skills, learning statistics',
    bio: 'Fifteen years in professional kitchens. I will teach you to cook confidently with what you already have in the fridge.',
    location: 'Porto, Portugal',
    timezone: 'Europe/Lisbon',
    languages: ['pt', 'en'],
    interests: ['Hobbies & crafts', 'Fitness & health', 'Community teaching'],
    teach: [
      {
        title: 'Knife skills in one hour',
        categoryId: 'wellbeing',
        level: 'beginner',
        format: 'video',
        duration: 60,
        description: 'Grip, the claw, three cuts, and how to keep an edge. Cook along with whatever vegetables you have.',
        outcomes: ['Safe grip and cutting technique', 'Julienne, dice and chiffonade', 'Sharpen a knife properly'],
        tags: ['cooking', 'knife-skills'],
      },
      {
        title: 'Meal planning on a budget',
        categoryId: 'life',
        level: 'any',
        format: 'chat',
        duration: 30,
        description: 'We build a week of meals around your budget, storage space and dietary needs, with a shopping list you can reuse.',
        outcomes: ['A one-week meal plan', 'Reusable shopping list', 'Batch-cooking schedule'],
        tags: ['budget', 'meal-planning'],
      },
    ],
    learnCategories: ['academics', 'business'],
  },
  {
    uid: 'demo_mei',
    email: 'mei@peerpulse.app',
    displayName: 'Mei Tanaka',
    headline: 'Data analyst trading spreadsheets for illustration',
    bio: 'I make sense of messy data for a living and I am slowly learning to draw. Patient with complete beginners.',
    location: 'Osaka, Japan',
    timezone: 'Asia/Tokyo',
    languages: ['ja', 'en'],
    interests: ['Career change', 'Exam preparation', 'Creative practice'],
    teach: [
      {
        title: 'Spreadsheets that actually work',
        categoryId: 'technology',
        level: 'beginner',
        format: 'video',
        duration: 60,
        description: 'Pivot tables, lookups and conditional formatting on your own messy file. We fix a real problem you have, not a sample dataset.',
        outcomes: ['Clean and structure a messy sheet', 'Use lookups confidently', 'Build a summary pivot table'],
        tags: ['spreadsheets', 'data', 'analytics'],
      },
      {
        title: 'Statistics for uni assignments',
        categoryId: 'academics',
        level: 'intermediate',
        format: 'video',
        duration: 60,
        description: 'Descriptive stats, hypothesis testing and how to write it up so your marker is happy. Bring your dataset.',
        outcomes: ['Choose the right test', 'Interpret p-values honestly', 'Write a results section'],
        tags: ['statistics', 'study'],
      },
    ],
    learnCategories: ['design', 'wellbeing'],
  },
  {
    uid: 'demo_amara',
    email: 'amara@peerpulse.app',
    displayName: 'Amara Nwosu',
    headline: 'Product designer, lifeguard-trained swim coach',
    bio: 'I design interfaces and I coach nervous adult swimmers. Both are about making the next step feel safe.',
    location: 'Lagos, Nigeria',
    timezone: 'Africa/Lagos',
    languages: ['en', 'sw'],
    interests: ['Creative practice', 'Fitness & health', 'Mentoring beginners'],
    teach: [
      {
        title: 'UI design critique',
        categoryId: 'design',
        level: 'intermediate',
        format: 'video',
        duration: 45,
        description: 'Bring a screen you are stuck on. We work through hierarchy, spacing, contrast and accessibility together.',
        outcomes: ['A revised layout', 'An accessibility checklist', 'A clearer typographic scale'],
        tags: ['ui', 'design-review', 'accessibility'],
      },
      {
        title: 'Figma fundamentals',
        categoryId: 'design',
        level: 'beginner',
        format: 'video',
        duration: 60,
        description: 'Frames, auto-layout, components and variants — the four things that make Figma click.',
        outcomes: ['Build a responsive frame', 'Create reusable components', 'Share a clean handoff file'],
        tags: ['figma', 'prototyping'],
      },
    ],
    learnCategories: ['technology', 'business'],
  },
  {
    uid: 'demo_tomas',
    email: 'tomas@peerpulse.app',
    displayName: 'Tomás Herrera',
    headline: 'Spanish teacher swapping lessons for guitar',
    bio: 'Certified DELE examiner. I run conversational Spanish sessions and I am learning guitar from scratch — I know exactly how it feels.',
    location: 'Valencia, Spain',
    timezone: 'Europe/Madrid',
    languages: ['es', 'en', 'fr'],
    interests: ['Learning a language', 'Exam preparation', 'Community teaching'],
    teach: [
      {
        title: 'Spanish conversation hour',
        categoryId: 'languages',
        level: 'any',
        format: 'voice',
        duration: 60,
        description: 'A full hour in Spanish at your level, with a vocabulary sheet and corrections sent afterwards.',
        outcomes: ['Speak for a full hour', 'A personalised vocabulary sheet', 'Pronunciation corrections'],
        tags: ['spanish', 'conversation', 'dele'],
      },
      {
        title: 'DELE exam strategy',
        categoryId: 'languages',
        level: 'advanced',
        format: 'video',
        duration: 90,
        description: 'Past-paper walkthrough for B2 and C1 with time-management tactics for each paper.',
        outcomes: ['A per-paper time plan', 'Marking criteria decoded', 'Two practice tasks marked'],
        tags: ['dele', 'exam', 'spanish'],
      },
    ],
    learnCategories: ['music', 'technology'],
  },
  {
    uid: 'demo_jonas',
    email: 'jonas@peerpulse.app',
    displayName: 'Jonas Berg',
    headline: 'Bike mechanic, maths tutor on the side',
    bio: 'I run a small repair workshop and tutor maths for teenagers. Happy to trade either for help with my website.',
    location: 'Malmö, Sweden',
    timezone: 'Europe/Stockholm',
    languages: ['en', 'de'],
    interests: ['Hobbies & crafts', 'Exam preparation', 'Coding side projects'],
    teach: [
      {
        title: 'Bicycle maintenance basics',
        categoryId: 'life',
        level: 'beginner',
        format: 'video',
        duration: 60,
        description: 'Brakes, gears, tyres and the five checks that catch problems before they strand you.',
        outcomes: ['Adjust brakes and gears', 'Fix a puncture confidently', 'A monthly maintenance checklist'],
        tags: ['bicycle', 'repair', 'diy'],
      },
      {
        title: 'Algebra without the fear',
        categoryId: 'academics',
        level: 'beginner',
        format: 'video',
        duration: 45,
        description: 'Rearranging equations, factorising and word problems, explained with physical examples you can picture.',
        outcomes: ['Rearrange any linear equation', 'Factorise quadratics', 'Translate word problems into algebra'],
        tags: ['maths', 'algebra', 'tutoring'],
      },
    ],
    learnCategories: ['technology', 'design'],
  },
  {
    uid: 'demo_admin',
    email: DEMO_CREDENTIALS.admin.email,
    displayName: 'Priya Raman',
    headline: 'PeerPulse steward',
    bio: 'Community steward for PeerPulse. I review reports, resolve disputes and keep the time-banking rules fair for everyone.',
    location: 'Remote',
    timezone: 'UTC',
    languages: ['en'],
    interests: ['Community teaching', 'Remote collaboration'],
    teach: [
      {
        title: 'Facilitating fair group decisions',
        categoryId: 'business',
        level: 'any',
        format: 'video',
        duration: 60,
        description: 'Practical facilitation techniques for community groups making decisions without money.',
        outcomes: ['Run a consent-based decision', 'Handle dominant voices', 'Document outcomes fairly'],
        tags: ['facilitation', 'community'],
      },
    ],
    learnCategories: ['design', 'technology'],
    role: 'admin',
  },
]

function daysAgo(days: number, hour: number, minute = 0): Date {
  const d = new Date(Date.now() - days * DAY)
  d.setHours(hour, minute, 0, 0)
  return d
}

function daysAhead(days: number, hour: number, minute = 0): Date {
  const d = new Date(Date.now() + days * DAY)
  d.setHours(hour, minute, 0, 0)
  return d
}

const iso = (d: Date): IsoDate => d.toISOString()

function emptyStats() {
  return {
    sessionsCompleted: 0,
    sessionsTaught: 0,
    teachingHours: 0,
    learningHours: 0,
    ratingSum: 0,
    reviewCount: 0,
    tokensEarned: 0,
    tokensSpent: 0,
  }
}

export interface SeedResult {
  config: PlatformConfig
  memberCount: number
}

/** Populate an empty database with a coherent demo world. */
export function seedLocalDatabase(db: LocalDatabase): SeedResult {
  const config: PlatformConfig = JSON.parse(JSON.stringify(DEFAULT_PLATFORM_CONFIG))
  db.config = config
  const now = new Date()
  const grant = signupGrantAmount(config)

  /* ── members, wallets, skills ───────────────────────────────────────── */
  const skillIdsByOwner: Record<string, string[]> = {}

  for (const spec of MEMBERS) {
    const createdAt = iso(daysAgo(60, 9))
    const profile: UserProfile = {
      uid: spec.uid,
      email: spec.email,
      displayName: spec.displayName,
      photoURL: null,
      avatarSeed: spec.uid,
      headline: spec.headline,
      bio: spec.bio,
      location: spec.location,
      timezone: spec.timezone,
      role: spec.role ?? 'member',
      status: 'active',
      interests: spec.interests,
      languages: spec.languages,
      teachSkillIds: [],
      learnSkillIds: [],
      teachCategories: [...new Set(spec.teach.map((s) => s.categoryId))],
      learnCategories: spec.learnCategories,
      preferredFormats: ['video', 'voice'],
      availability: [
        { weekday: 1, start: '18:00', end: '21:00' },
        { weekday: 3, start: '18:00', end: '21:00' },
        { weekday: 6, start: '10:00', end: '14:00' },
      ],
      privacy: {
        profileVisibility: 'public',
        showEmail: false,
        showAvailability: true,
        allowDirectRequests: true,
        appearInDiscovery: true,
      },
      stats: emptyStats(),
      onboarding: { completed: true, step: 5, completedAt: createdAt, savedAt: createdAt, skipped: false },
      createdAt,
      updatedAt: iso(daysAgo(1, 12)),
      lastActiveAt: iso(daysAgo(0, 8)),
    }
    db.users[spec.uid] = profile

    // Wallet + documented signup grant, recorded in the ledger.
    const wallet: Wallet = {
      uid: spec.uid,
      balance: 0,
      held: 0,
      lifetimeEarned: 0,
      lifetimeSpent: 0,
      lifetimeGranted: 0,
      policyVersion: config.version,
      updatedAt: createdAt,
      updatedBy: 'system:signup',
    }
    if (grant > 0) {
      const grantId = `tx_grant_${spec.uid}`
      wallet.balance += grant
      wallet.lifetimeGranted += grant
      db.transactions[grantId] = {
        id: grantId,
        type: 'signup_grant',
        amount: grant,
        direction: 'credit',
        status: 'posted',
        uid: spec.uid,
        counterpartyUid: null,
        bookingId: null,
        roomId: null,
        idempotencyKey: grantId,
        balanceAfter: wallet.balance,
        reason: 'Welcome grant — new members may receive introductory Time Tokens.',
        policyCode: 'signup_grant',
        createdBy: 'system:signup',
        createdAt,
      }
    }
    db.wallets[spec.uid] = wallet

    // Skill listings
    const ids: string[] = []
    for (const skill of spec.teach) {
      const id = `skill_${spec.uid.replace('demo_', '')}_${slugify(skill.title)}`
      ids.push(id)
      const listing: SkillListing = {
        id,
        ownerUid: spec.uid,
        title: skill.title,
        slug: slugify(skill.title),
        categoryId: skill.categoryId,
        description: skill.description,
        outcomes: skill.outcomes,
        level: skill.level,
        languages: spec.languages,
        format: skill.format,
        durationMinutes: skill.duration,
        tags: skill.tags,
        status: 'published',
        moderation: { state: 'clean', reason: null, reviewedByUid: null, reviewedAt: null },
        bookingCount: 0,
        completedCount: 0,
        ratingSum: 0,
        reviewCount: 0,
        createdAt: iso(daysAgo(45, 10)),
        updatedAt: iso(daysAgo(6, 15)),
      }
      db.skills[id] = listing
    }
    profile.teachSkillIds = ids
    skillIdsByOwner[spec.uid] = ids
  }

  // Everyone wants to learn something that somebody else teaches.
  db.users.demo_sam.learnSkillIds = [skillIdsByOwner.demo_lena[0]]
  db.users.demo_lena.learnSkillIds = [skillIdsByOwner.demo_tomas[0]]
  db.users.demo_paulo.learnSkillIds = [skillIdsByOwner.demo_mei[1]]
  db.users.demo_mei.learnSkillIds = [skillIdsByOwner.demo_amara[1]]
  db.users.demo_amara.learnSkillIds = [skillIdsByOwner.demo_lena[0]]
  db.users.demo_tomas.learnSkillIds = [skillIdsByOwner.demo_sam[0]]
  db.users.demo_jonas.learnSkillIds = [skillIdsByOwner.demo_amara[0]]
  db.users.demo_admin.learnSkillIds = [skillIdsByOwner.demo_mei[0]]

  /* ── historical sessions, settled through the real domain logic ─────── */
  interface HistorySpec {
    id: string
    teacherUid: string
    learnerUid: string
    skillId: string
    when: Date
    durationMinutes: number
    /** Fraction of the booked duration both members actually attended. */
    attendance: number
    verifiedMinutes?: number
    review?: { rating: number; comment: string; subject: 'teacher' | 'learner' }
  }

  const history: HistorySpec[] = [
    {
      id: 'bk_1001',
      teacherUid: 'demo_lena',
      learnerUid: 'demo_sam',
      skillId: skillIdsByOwner.demo_lena[0],
      when: daysAgo(21, 18),
      durationMinutes: 90,
      attendance: 0.95,
      review: { rating: 5, comment: 'Lena explained components with a real example and I deployed my first app the same evening.', subject: 'teacher' },
    },
    {
      id: 'bk_1002',
      teacherUid: 'demo_sam',
      learnerUid: 'demo_tomas',
      skillId: skillIdsByOwner.demo_sam[0],
      when: daysAgo(17, 19),
      durationMinutes: 60,
      attendance: 1,
      review: { rating: 5, comment: 'Sam is endlessly patient. I went from never holding a guitar to playing a song in an hour.', subject: 'teacher' },
    },
    {
      id: 'bk_1003',
      teacherUid: 'demo_tomas',
      learnerUid: 'demo_lena',
      skillId: skillIdsByOwner.demo_tomas[0],
      when: daysAgo(14, 17),
      durationMinutes: 60,
      attendance: 0.9,
      review: { rating: 5, comment: 'A whole hour in Spanish with useful corrections afterwards. Exactly what I needed.', subject: 'teacher' },
    },
    {
      id: 'bk_1004',
      teacherUid: 'demo_amara',
      learnerUid: 'demo_jonas',
      skillId: skillIdsByOwner.demo_amara[0],
      when: daysAgo(11, 16),
      durationMinutes: 45,
      attendance: 0.85,
      review: { rating: 4, comment: 'Very practical critique — my contrast and spacing are much better now.', subject: 'teacher' },
    },
    {
      id: 'bk_1005',
      teacherUid: 'demo_mei',
      learnerUid: 'demo_paulo',
      skillId: skillIdsByOwner.demo_mei[1],
      when: daysAgo(8, 20),
      durationMinutes: 60,
      attendance: 1,
      review: { rating: 5, comment: 'Mei walked me through hypothesis testing using my actual sales data.', subject: 'teacher' },
    },
    {
      id: 'bk_1006',
      teacherUid: 'demo_jonas',
      learnerUid: 'demo_mei',
      skillId: skillIdsByOwner.demo_jonas[0],
      when: daysAgo(5, 15),
      durationMinutes: 60,
      attendance: 0.8,
      verifiedMinutes: 48,
      review: { rating: 4, comment: 'Clear and calm. I fixed my own brakes the next morning.', subject: 'teacher' },
    },
    {
      id: 'bk_1007',
      teacherUid: 'demo_amara',
      learnerUid: 'demo_mei',
      skillId: skillIdsByOwner.demo_amara[1],
      when: daysAgo(3, 14),
      durationMinutes: 60,
      attendance: 0.92,
      review: { rating: 5, comment: 'Auto-layout finally makes sense. Great pacing for a beginner.', subject: 'teacher' },
    },
  ]

  for (const spec of history) {
    const start = spec.when
    const end = new Date(start.getTime() + spec.durationMinutes * 60_000)
    const teacher = db.users[spec.teacherUid]
    const learner = db.users[spec.learnerUid]
    const skill = db.skills[spec.skillId]
    const tokenAmount = computeTokenAmount(spec.durationMinutes, config)

    // Attendance segments: both members join slightly after the hour and leave
    // near the end, mirroring how a real session overlaps.
    const joinOffset = (1 - spec.attendance) * spec.durationMinutes * 60_000 * 0.5
    const attendance: AttendanceSegment[] = [
      {
        uid: spec.teacherUid,
        joinedAt: iso(new Date(start.getTime() + joinOffset * 0.4)),
        leftAt: iso(new Date(end.getTime() - joinOffset * 0.2)),
      },
      {
        uid: spec.learnerUid,
        joinedAt: iso(new Date(start.getTime() + joinOffset * 0.8)),
        leftAt: iso(new Date(end.getTime() - joinOffset * 0.5)),
      },
    ]

    const verifiedMinutes = spec.verifiedMinutes ?? Math.min(spec.durationMinutes, Math.round(spec.durationMinutes * spec.attendance))
    const roomId = `room_${spec.id}`
    const settledAt = iso(new Date(end.getTime() + 5 * 60_000))

    const booking: Booking = {
      id: spec.id,
      skillId: spec.skillId,
      skillTitle: skill.title,
      categoryId: skill.categoryId,
      teacherUid: spec.teacherUid,
      learnerUid: spec.learnerUid,
      participants: [spec.teacherUid, spec.learnerUid].sort(),
      participantsSnapshot: [
        { uid: spec.teacherUid, displayName: teacher.displayName, photoURL: null, avatarSeed: teacher.avatarSeed },
        { uid: spec.learnerUid, displayName: learner.displayName, photoURL: null, avatarSeed: learner.avatarSeed },
      ],
      createdByUid: spec.learnerUid,
      startAt: iso(start),
      endAt: iso(end),
      durationMinutes: spec.durationMinutes,
      timezone: learner.timezone,
      status: 'completed',
      roomId,
      tokenAmount,
      settlement: {
        state: 'settled',
        settlementId: `settlement_${spec.id}`,
        settledAt,
        debitTxId: `tx_${spec.id}_debit`,
        creditTxId: `tx_${spec.id}_credit`,
        refundTxId: null,
        heldTxId: null,
        note: 'Settled automatically after the session window closed.',
      },
      cancellation: null,
      reschedules: [],
      completion: {
        teacherConfirmedAt: settledAt,
        learnerConfirmedAt: settledAt,
        autoCompletedAt: settledAt,
        verifiedMinutes,
        closedBy: 'auto_settle',
      },
      learnerNote: 'Looking forward to it!',
      teacherNote: '',
      revision: 3,
      createdAt: iso(new Date(start.getTime() - 6 * DAY)),
      updatedAt: settledAt,
    }
    db.bookings[booking.id] = booking

    const room: Room = {
      id: roomId,
      bookingId: booking.id,
      skillTitle: skill.title,
      teacherUid: spec.teacherUid,
      learnerUid: spec.learnerUid,
      participants: booking.participants,
      status: 'closed',
      createdAt: booking.createdAt,
      openedAt: iso(new Date(start.getTime() + joinOffset * 0.4)),
      closedAt: settledAt,
      attendanceLocked: true,
      session: {
        startedAt: iso(new Date(start.getTime() + joinOffset * 0.4)),
        endedAt: iso(new Date(end.getTime() - joinOffset * 0.2)),
        durationMinutes: spec.durationMinutes,
        initiatorUid: spec.teacherUid,
      },
    }
    db.rooms[roomId] = room
    db.attendance[roomId] = attendance

    // Ledger: run the same settlement builder the Cloud Function uses.
    const write = buildSettlementWrites({
      booking,
      plan: {
        outcome: 'settle',
        tokenAmount,
        creditAmount: tokenAmount,
        debitAmount: tokenAmount,
        refundAmount: 0,
        verifiedMinutes,
        policyCode: 'standard_settlement',
        reason: `Auto-settled after the session window closed (${verifiedMinutes} min verified).`,
      },
      teacher: db.wallets[spec.teacherUid],
      learner: db.wallets[spec.learnerUid],
      createdBy: 'system:auto_settle',
      reason: `Completed: ${skill.title}`,
    })
    for (const entry of write.entries) {
      db.transactions[entry.id] = {
        id: entry.id,
        type: entry.type,
        amount: entry.amount,
        direction: entry.direction,
        status: 'posted',
        uid: entry.uid,
        counterpartyUid: entry.counterpartyUid,
        bookingId: entry.bookingId,
        roomId,
        idempotencyKey: entry.idempotencyKey,
        balanceAfter: entry.balanceAfter,
        reason: entry.reason,
        policyCode: entry.policyCode,
        createdBy: entry.createdBy,
        createdAt: settledAt,
      }
    }
    db.wallets[spec.teacherUid] = write.nextTeacher
    db.wallets[spec.learnerUid] = write.nextLearner

    db.settlements[`settlement_${spec.id}`] = {
      id: `settlement_${spec.id}`,
      bookingId: spec.id,
      teacherUid: spec.teacherUid,
      learnerUid: spec.learnerUid,
      tokenAmount,
      verifiedMinutes,
      status: 'settled',
      debitTxId: `tx_${spec.id}_debit`,
      creditTxId: `tx_${spec.id}_credit`,
      refundTxId: null,
      reason: `Auto-settled after the session window closed (${verifiedMinutes} min verified).`,
      idempotencyKey: `settlement_${spec.id}`,
      attempts: 1,
      createdAt: settledAt,
      updatedAt: settledAt,
    }

    if (spec.review) {
      const reviewId = `rev_${spec.id}`
      const authorUid = spec.review.subject === 'teacher' ? spec.learnerUid : spec.teacherUid
      const subjectUid = spec.teacherUid
      const review: Review = {
        id: reviewId,
        bookingId: spec.id,
        skillId: spec.skillId,
        authorUid,
        subjectUid,
        authorRole: 'learner',
        rating: spec.review.rating,
        comment: spec.review.comment,
        tags: [],
        moderation: { state: 'clean', reason: null },
        responseText: null,
        responseAt: null,
        createdAt: iso(new Date(end.getTime() + 40 * 60_000)),
      }
      db.reviews[reviewId] = review
    }
  }

  /* ── upcoming + pending bookings ────────────────────────────────────── */
  const upcoming: Array<{
    id: string
    teacherUid: string
    learnerUid: string
    skillId: string
    start: Date
    durationMinutes: number
    status: Booking['status']
    note: string
  }> = [
    {
      id: 'bk_2001',
      teacherUid: 'demo_mei',
      learnerUid: 'demo_sam',
      skillId: skillIdsByOwner.demo_mei[0],
      start: daysAhead(2, 18),
      durationMinutes: 60,
      status: 'confirmed',
      note: 'I have a messy invoice tracker — would love to fix it live.',
    },
    {
      id: 'bk_2002',
      teacherUid: 'demo_sam',
      learnerUid: 'demo_lena',
      skillId: skillIdsByOwner.demo_sam[1],
      start: daysAhead(4, 20),
      durationMinutes: 30,
      status: 'requested',
      note: 'Sharing a demo of a song I have been working on.',
    },
    {
      id: 'bk_2003',
      teacherUid: 'demo_lena',
      learnerUid: 'demo_amara',
      skillId: skillIdsByOwner.demo_lena[0],
      start: daysAhead(6, 17),
      durationMinutes: 90,
      status: 'confirmed',
      note: 'Want to rebuild my portfolio in Vue.',
    },
    {
      id: 'bk_2004',
      teacherUid: 'demo_jonas',
      learnerUid: 'demo_paulo',
      skillId: skillIdsByOwner.demo_jonas[1],
      start: daysAgo(2, 16),
      durationMinutes: 45,
      status: 'cancelled',
      note: 'Rescheduling after a work clash.',
    },
  ]

  for (const spec of upcoming) {
    const skill = db.skills[spec.skillId]
    const teacher = db.users[spec.teacherUid]
    const learner = db.users[spec.learnerUid]
    const end = new Date(spec.start.getTime() + spec.durationMinutes * 60_000)
    const tokenAmount = computeTokenAmount(spec.durationMinutes, config)
    const cancelled = spec.status === 'cancelled'
    const roomId = spec.status === 'confirmed' ? `room_${spec.id}` : null

    db.bookings[spec.id] = {
      id: spec.id,
      skillId: spec.skillId,
      skillTitle: skill.title,
      categoryId: skill.categoryId,
      teacherUid: spec.teacherUid,
      learnerUid: spec.learnerUid,
      participants: [spec.teacherUid, spec.learnerUid].sort(),
      participantsSnapshot: [
        { uid: spec.teacherUid, displayName: teacher.displayName, photoURL: null, avatarSeed: teacher.avatarSeed },
        { uid: spec.learnerUid, displayName: learner.displayName, photoURL: null, avatarSeed: learner.avatarSeed },
      ],
      createdByUid: spec.learnerUid,
      startAt: iso(spec.start),
      endAt: iso(end),
      durationMinutes: spec.durationMinutes,
      timezone: learner.timezone,
      status: spec.status,
      roomId,
      tokenAmount,
      settlement: {
        state: cancelled ? 'refunded' : 'unsettled',
        settlementId: null,
        settledAt: null,
        debitTxId: null,
        creditTxId: null,
        refundTxId: null,
        heldTxId: null,
        note: cancelled ? 'Cancelled inside the free window — nothing was charged.' : null,
      },
      cancellation: cancelled
        ? {
            byUid: spec.learnerUid,
            reason: 'Work travel came up — hope to rebook soon.',
            at: iso(new Date(spec.start.getTime() - 3 * DAY)),
            refundTokens: tokenAmount,
            policyCode: 'free_window_cancellation',
          }
        : null,
      reschedules: [],
      completion: {
        teacherConfirmedAt: null,
        learnerConfirmedAt: null,
        autoCompletedAt: null,
        verifiedMinutes: null,
        closedBy: null,
      },
      learnerNote: spec.note,
      teacherNote: '',
      revision: 1,
      createdAt: iso(new Date(spec.start.getTime() - 5 * DAY)),
      updatedAt: iso(new Date(spec.start.getTime() - DAY)),
    }

    if (roomId) {
      db.rooms[roomId] = {
        id: roomId,
        bookingId: spec.id,
        skillTitle: skill.title,
        teacherUid: spec.teacherUid,
        learnerUid: spec.learnerUid,
        participants: [spec.teacherUid, spec.learnerUid].sort(),
        status: 'scheduled',
        createdAt: iso(new Date(spec.start.getTime() - 5 * DAY)),
        openedAt: null,
        closedAt: null,
        attendanceLocked: false,
        session: { startedAt: null, endedAt: null, durationMinutes: null, initiatorUid: null },
      }
      db.presence[roomId] = []
      db.attendance[roomId] = []
      db.signals[roomId] = []
      db.candidates[roomId] = []
    }
  }

  /* ── communities ───────────────────────────────────────────────────── */
  const communitySpecs: Array<{
    id: string
    name: string
    description: string
    categoryId: string
    visibility: Community['visibility']
    ownerUid: string
    memberUids: string[]
    tags: string[]
    rules: string[]
    posts: Array<{ kind: CommunityPost['kind']; authorUid: string; title: string; body: string; reactions: string[]; comments: Array<{ authorUid: string; body: string }> }>
  }> = [
    {
      id: 'cm_guitar',
      name: 'Guitar Circle',
      description: 'Practice partners, feedback on recordings and monthly challenges for players at every level.',
      categoryId: 'music',
      visibility: 'public',
      ownerUid: 'demo_sam',
      memberUids: ['demo_sam', 'demo_tomas', 'demo_mei', 'demo_jonas'],
      tags: ['guitar', 'practice', 'feedback'],
      rules: ['Be kind about early attempts', 'Tag your playing level', 'One practice log post per week'],
      posts: [
        {
          kind: 'post',
          authorUid: 'demo_sam',
          title: '30-day chord change challenge — join me?',
          body: 'Pick two chords you always fumble and switch between them for five minutes a day. Post your count here each week. I started at 24 changes a minute and I am at 51 now.',
          reactions: ['demo_tomas', 'demo_jonas'],
          comments: [
            { authorUid: 'demo_tomas', body: 'I am in — G to C is my nemesis.' },
            { authorUid: 'demo_jonas', body: 'Just what I needed to stop noodling aimlessly.' },
          ],
        },
        {
          kind: 'resource',
          authorUid: 'demo_tomas',
          title: 'Free ear-training drills that actually help',
          body: 'Ten minutes before practice, no instrument in hand. I have been doing interval recognition for a month and my songwriting has changed.',
          reactions: ['demo_sam'],
          comments: [],
        },
      ],
    },
    {
      id: 'cm_coders',
      name: 'First Build Club',
      description: 'Supportive space for people shipping their first real project. Ask anything — no question is too basic.',
      categoryId: 'technology',
      visibility: 'public',
      ownerUid: 'demo_lena',
      memberUids: ['demo_lena', 'demo_sam', 'demo_amara', 'demo_jonas', 'demo_mei'],
      tags: ['vue', 'beginners', 'shipping'],
      rules: ['Share work in progress, not just finished work', 'Explain jargon when you use it', 'Offer one concrete suggestion per critique'],
      posts: [
        {
          kind: 'question',
          authorUid: 'demo_sam',
          title: 'How do I know when a component is too big?',
          body: 'Mine is around 300 lines and it feels unwieldy, but splitting it creates ten tiny files. Where is the balance?',
          reactions: ['demo_lena', 'demo_amara'],
          comments: [
            { authorUid: 'demo_lena', body: 'A good trigger: if you describe it with the word "and" more than twice, it wants to be two components.' },
            { authorUid: 'demo_amara', body: 'I use the same instinct for design files. Sections that change for different reasons belong apart.' },
          ],
        },
        {
          kind: 'event',
          authorUid: 'demo_lena',
          title: 'Group code review hour (all levels)',
          body: 'Bring one file you are unsure about. We read each other code aloud, out loud, kindly.',
          reactions: ['demo_sam'],
          comments: [],
        },
      ],
    },
    {
      id: 'cm_language',
      name: 'Language Exchange Lounge',
      description: 'Find conversation partners, swap corrections and keep a streak going across nine languages.',
      categoryId: 'languages',
      visibility: 'public',
      ownerUid: 'demo_tomas',
      memberUids: ['demo_tomas', 'demo_lena', 'demo_sam', 'demo_mei'],
      tags: ['conversation', 'practice', 'corrections'],
      rules: ['Correct gently and briefly', 'Reply in the language you are learning', 'No unsolicited grammar lectures'],
      posts: [
        {
          kind: 'post',
          authorUid: 'demo_tomas',
          title: 'The five-minute rule for keeping a streak',
          body: 'On a busy day, do five minutes on the platform instead of zero. Consistency beats intensity — I have data from my own students.',
          reactions: ['demo_lena', 'demo_mei', 'demo_sam'],
          comments: [{ authorUid: 'demo_lena', body: 'This is exactly what got me through last month.' }],
        },
      ],
    },
  ]

  for (const spec of communitySpecs) {
    const owner = db.users[spec.ownerUid]
    const createdAt = iso(daysAgo(40, 11))
    const community: Community = {
      id: spec.id,
      name: spec.name,
      slug: slugify(spec.name),
      description: spec.description,
      categoryId: spec.categoryId,
      visibility: spec.visibility,
      ownerUids: [spec.ownerUid],
      moderatorUids: [spec.ownerUid],
      memberCount: spec.memberUids.length,
      postCount: spec.posts.length,
      tags: spec.tags,
      rules: spec.rules,
      createdAt,
      updatedAt: iso(daysAgo(1, 9)),
    }
    db.communities[spec.id] = community
    db.communityMembers[spec.id] = spec.memberUids.map((uid) => {
      const member = db.users[uid]
      const role: CommunityMember['role'] = uid === spec.ownerUid ? 'owner' : 'member'
      return { uid, displayName: member.displayName, avatarSeed: member.avatarSeed, role, joinedAt: createdAt }
    })

    spec.posts.forEach((postSpec, index) => {
      const author = db.users[postSpec.authorUid]
      const postId = `post_${spec.id}_${index + 1}`
      const postCreatedAt = iso(new Date(now.getTime() - (index + 1) * 2 * DAY))
      const reactions: Record<string, string> = {}
      postSpec.reactions.forEach((uid, i) => {
        reactions[uid] = i % 3 === 0 ? '💡' : i % 3 === 1 ? '👏' : '❤️'
      })
      const comments: CommunityComment[] = postSpec.comments.map((c, ci) => ({
        id: `cmt_${postId}_${ci + 1}`,
        postId,
        communityId: spec.id,
        authorUid: c.authorUid,
        authorName: db.users[c.authorUid].displayName,
        authorSeed: db.users[c.authorUid].avatarSeed,
        body: c.body,
        moderation: { state: 'clean', reason: null },
        createdAt: iso(new Date(Date.parse(postCreatedAt) + (ci + 1) * 45 * 60_000)),
      }))
      comments.forEach((c) => {
        db.comments[c.id] = c
      })

      db.posts[postId] = {
        id: postId,
        communityId: spec.id,
        authorUid: postSpec.authorUid,
        authorName: author.displayName,
        authorSeed: author.avatarSeed,
        kind: postSpec.kind,
        title: postSpec.title,
        body: postSpec.body,
        link: null,
        reactions,
        commentCount: comments.length,
        pinned: index === 0 && spec.id === 'cm_coders',
        moderation: { state: 'clean', reason: null },
        event:
          postSpec.kind === 'event'
            ? {
                startAt: iso(daysAhead(5, 18)),
                durationMinutes: 60,
                location: 'PeerPulse video room · link shared on RSVP',
                capacity: 20,
              }
            : null,
        createdAt: postCreatedAt,
        updatedAt: postCreatedAt,
      }
    })
    void owner
  }

  /* ── notifications for the demo member ────────────────────────────────
   *
   * Composed by `shared/notify.ts`, like every notification the running app
   * writes. The seed used to hand-write these and the copy drifted from the real
   * thing (a `low`-priority reply with a title no composer produces). The `read`
   * flag and the timestamps stay hand-written: they are staging for the demo,
   * not content.
   */
  const upcomingBooking = requireSeedBooking(db, 'bk_2001')
  const settledBooking = Object.values(db.bookings).find(
    (b) => b.status === 'completed' && b.teacherUid === 'demo_sam',
  )
  if (!settledBooking) throw new Error('seed: no completed session for demo_sam to build notifications from')
  const notifications: Array<NotificationDraft & { at: string; read: boolean }> = [
    {
      ...bookingConfirmedDraft(upcomingBooking, requireSeedUser(db, upcomingBooking.teacherUid).displayName),
      read: false,
      at: iso(new Date(now.getTime() - 3 * HOUR)),
    },
    {
      ...sessionSettledDraft(settledBooking, 1, 'teacher'),
      read: false,
      at: iso(new Date(now.getTime() - 17 * DAY)),
    },
    {
      ...commentReplyDraft({
        recipientUid: 'demo_sam',
        authorName: 'Lena Fischer',
        communityId: 'cm_coders',
        postId: 'po_coders_1',
        postTitle: 'your post',
        commentBody: 'A good trigger: if you describe it with the word "and" more than twice…',
      }),
      read: true,
      at: iso(new Date(now.getTime() - 2 * DAY)),
    },
    {
      ...tokenGrantDraft('demo_sam', 3, 'Welcome grant — new members may receive introductory Time Tokens.', { signup: true }),
      read: true,
      at: iso(daysAgo(60, 9)),
    },
  ]

  notifications.forEach((n, i) => {
    const id = `ntf_demo_sam_${i + 1}`
    db.notifications[id] = {
      id,
      uid: n.uid,
      type: n.type,
      title: n.title,
      body: n.body,
      link: n.link,
      read: n.read,
      priority: n.priority,
      createdAt: n.at,
    }
  })

  /* ── moderation queue: one report, one dispute ──────────────────────── */
  db.reports.rpt_1001 = {
    id: 'rpt_1001',
    reporterUid: 'demo_jonas',
    targetType: 'post',
    targetId: 'post_cm_coders_2',
    targetPath: 'communities/cm_coders/posts/post_cm_coders_2',
    targetLabel: 'Group code review hour (all levels)',
    reason: 'spam',
    details: 'The event link looks like it points to an external paid course rather than a free peer session.',
    status: 'open',
    priority: 'normal',
    resolution: null,
    handledByUid: null,
    handledAt: null,
    createdAt: iso(new Date(now.getTime() - 26 * HOUR)),
    updatedAt: iso(new Date(now.getTime() - 26 * HOUR)),
  }

  db.disputes.dsp_1001 = {
    id: 'dsp_1001',
    bookingId: 'bk_1004',
    openedByUid: 'demo_jonas',
    againstUid: 'demo_amara',
    claim: 'The session was cut short after 25 minutes because of our connection, so I would like the details reviewed.',
    evidence: 'Session ended early; I offered to rebook but we have not found a slot.',
    status: 'open',
    outcome: null,
    handledByUid: null,
    createdAt: iso(new Date(now.getTime() - 4 * DAY)),
    updatedAt: iso(new Date(now.getTime() - 4 * DAY)),
  }

  recomputeDerivedCounters(db)
  db.seededAt = iso(now)
  verifySeedIntegrity(db)

  return { config, memberCount: MEMBERS.length }
}

/**
 * Derive every denormalised counter from the facts, once the world exists.
 *
 * The seed creates bookings, settlements, ledger rows and reviews; the counters
 * they imply (listing scores, completed-session counts, each member's hours and
 * token totals) are then computed here from the data itself, through the same
 * shared helpers the settlement engine and the Cloud Functions use.
 *
 * Two reasons it is derived rather than incremented at creation time. First, the
 * increments are easy to get subtly wrong — a booking created in one branch and
 * cancelled in another, a review about the teacher versus about the learner — and
 * this file has been wrong in exactly those ways before. Second, the totals must
 * equal what the ledger and the bookings say, because that is the promise the
 * product makes: every number on screen is auditable. `tests/unit/seedIntegrity.spec.ts`
 * re-derives all of them independently and fails if this pass and the data ever
 * disagree.
 */
export function recomputeDerivedCounters(db: LocalDatabase): void {
  const bookings = Object.values(db.bookings)
  const reviews = Object.values(db.reviews)

  for (const listing of Object.values(db.skills)) {
    const mine = bookings.filter((booking) => booking.skillId === listing.id)
    const settled = mine.filter((booking) => ['settled', 'partial'].includes(booking.settlement.state))
    const about = reviews.filter((review) => review.skillId === listing.id && review.subjectUid === listing.ownerUid)

    listing.bookingCount = mine.reduce((count) => listingAfterBooking({ bookingCount: count }).bookingCount, 0)
    listing.completedCount = settled.reduce((count) => listingAfterSettlement({ completedCount: count }).completedCount, 0)
    listing.reviewCount = about.reduce((count) => listingAfterReview({ ratingSum: 0, reviewCount: count }, 0).reviewCount, 0)
    listing.ratingSum = roundTokens(about.reduce((sum, review) => sum + review.rating, 0))
  }

  for (const profile of Object.values(db.users)) {
    const empty = {
      sessionsCompleted: 0,
      sessionsTaught: 0,
      teachingHours: 0,
      learningHours: 0,
      ratingSum: 0,
      reviewCount: 0,
      tokensEarned: 0,
      tokensSpent: 0,
    }
    let stats = empty

    // Sessions, hours and token totals from the settled bookings, taking the
    // amounts the ledger actually moved rather than the session's nominal worth.
    for (const booking of bookings) {
      if (!['settled', 'partial'].includes(booking.settlement.state)) continue
      const balance = db.transactions[`tx_${booking.id}_debit`]
      const amounts = {
        creditAmount: db.transactions[`tx_${booking.id}_credit`]?.amount ?? balance?.amount ?? 0,
        debitAmount: balance?.amount ?? 0,
      }
      if (booking.teacherUid === profile.uid) {
        stats = statsAfterSettlement(stats, 'teacher', booking.durationMinutes, amounts)
      }
      if (booking.learnerUid === profile.uid) {
        stats = statsAfterSettlement(stats, 'learner', booking.durationMinutes, amounts)
      }
    }

    // Ratings from the reviews about this member.
    for (const review of reviews.filter((r) => r.subjectUid === profile.uid)) {
      stats = statsAfterReview(stats, review.rating)
    }

    // Token totals come from the ledger itself, so the profile and the wallet
    // can never tell different stories about the same member.
    const rows = Object.values(db.transactions).filter((row) => row.uid === profile.uid && row.status === 'posted')
    stats.tokensEarned = roundTokens(
      rows.filter((row) => row.direction === 'credit' && row.type !== 'signup_grant').reduce((sum, row) => sum + row.amount, 0),
    )
    stats.tokensSpent = roundTokens(rows.filter((row) => row.direction === 'debit').reduce((sum, row) => sum + row.amount, 0))

    profile.stats = { ...profile.stats, ...stats }
  }
}

/**
 * Guard rail: seeded wallets must match the ledger exactly. If this ever fails
 * the demo data is wrong, and it is far better to know at seed time than to
 * show a wrong balance in the UI.
 */
export function verifySeedIntegrity(db: LocalDatabase): void {
  for (const wallet of Object.values(db.wallets)) {
    const entries = Object.values(db.transactions).filter((t) => t.uid === wallet.uid)
    const granted = entries.filter((t) => t.type === 'signup_grant').reduce((sum, t) => sum + t.amount, 0)
    const earned = entries
      .filter((t) => t.type === 'credit' && t.status === 'posted')
      .reduce((sum, t) => sum + t.amount, 0)
    const spent = entries
      .filter((t) => t.direction === 'debit' && t.status === 'posted')
      .reduce((sum, t) => sum + t.amount, 0)
    const expected = Math.round((granted + earned - spent) * 10_000) / 10_000
    if (Math.abs(expected - wallet.balance) > 0.0001) {
      throw new Error(
        `Seed integrity error for ${wallet.uid}: wallet balance ${wallet.balance} does not match ledger ${expected}.`,
      )
    }
  }
}

/** Merge overlapping presence windows — used by the room UI for "time on air". */
export function seedAttendanceWindows(db: LocalDatabase, roomId: string) {
  return mergeWindows(
    (db.attendance[roomId] ?? []).map((segment) => ({
      start: segment.joinedAt,
      end: segment.leftAt ?? new Date().toISOString(),
    })),
  )
}
